### ISSUE TITLE
Running on Centos 7 throws C99 /C11 compatibility issues

### ISSUE THREAD

**Issue by naimavahab** [karpathy/llama2.c#100]
I had to specify -std=c99 while compiling run.c ; after that as well its throwing exceptions .. what is the GCC version needed and any specifications to use in Linux systems

**Comment by love01211** [comment]
Same question

**Comment by emma-eva** [comment]
you can try using `-std=gnu11` or `-std=gnu99`

**Comment by bfjm** [comment]
you can try -std=c11,and #include <time.h> to #include <linux/time.h>

**Comment by love01211** [comment]
@emma-eva You are right. I used the - std=gnu11 parameter and it can compile normally

**Comment by karpathy** [comment]
should we modify our Makefile potentially to include this configuration, with a comment?  Under a "runcentos" target or something like that?

**Comment by tairov** [comment]
@naimavahab @love01211 please pull latest master and then try `make rungnu` it should work now

**Comment by love01211** [comment]
Yes, everything is so perfect
