### ISSUE TITLE
conflicting sentences in generated stories

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [karpathy/llama2.c#107]
following sample generated from 44M model, do I need to set any hyper parameter(s) to fix this (or should i use bigger model?).  

```
~/llama2.c$ ./run out44m/model44m.bin
```
> \<s\>
>  Sara and her mom were going to the zoo. Sara was very happy. She wanted to see the lions and the monkeys and the birds. She did not mind that it was cloudy and cold outside.
> Mom said they had to take a taxi to get to the zoo. She told Sara to hold mom's hand and not to run away. Sara nodded and smiled. She liked taxis.
> They got in the taxi and Mom told the driver where they were going. The driver was a nice man. He said hello and asked where they were going. Mom told him that they were going to the zoo. The driver smiled and said okay.
> Sara looked out the window and saw many cars and trucks and buses. They were all different colors and sounds. She wondered what they were doing. Mom said they were going to a place that had animals. She said animals like cows, pigs, sheep and ducks.
> **_Sara did not like animals. She liked animals_**. They were fierce and loud and scary. She was afraid that they would bite her or kick her or chase her. She started to cry and said no. She said
> achieved tok/s: 25.934556

**Comment by karpathy** [comment]
Haha language models... yes use bigger model. The bigger the model the less confused the model. They're just parroting text to their best ability.
