### ISSUE TITLE
multiple stories are generated with Model-110M

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [karpathy/llama2.c#108]
following output generated from Model-110M. seems like to generate the desired number of output tokens  a new story is started instead of continuing one story. (update: model-44m also generated multiple stories)
```
~/llama2.c$ ./run out110m/model110m.bin
```
> \<s\>
>  **Once upon a time, there was a little girl named Lily**. She had a cat named Mittens. Mittens was very fluffy and loved to sleep in the sun. One day, Lily went to the park and saw a new friend. His name was Max and he had a dog named Spot. Lily and her new friend played together and had so much fun. They talked about their favorite toys and pets. Mittens even joined in the fun and purred loudly. Lily was happy to have a new friend to play with and talk to.
> \<s\>
>  **Once upon a time, there was a clever cat named Tom**. Tom had a big smile that made everyone happy. He lived in a small house with a small girl named Sue. Sue and Tom loved to play together all day long.
> One day, Sue and Tom were playing with their toys when Sue fell down. She hurt her thumb and started to cry. Tom wanted to help Sue feel better. He thought hard and came up with a plan.
> Tom found a soft cloth and wrapped it around Sue's thumb. He gave her a gentle kiss on her thumb to make it feel better. Sue stopped crying and started to smile. She knew that Tom was
> achieved tok/s: 9.483940

**Comment by karpathy** [comment]
Yes. I want the code to be agnostic to the dataset, so we by default always run 256 tokens. This can be multiple stories, it's okay.

**Comment by karpathy** [comment]
(The stories are not cropped, they are done. Or the model thinks so.)
