### ISSUE TITLE
ModuleNotFoundError: No module named 'llama'

### ISSUE THREAD

**Issue by pantol** [karpathy/llama2.c#127]
I am trying to export the llama weight to the directory of llama2.c but once I have initialize the script I got error 

`Traceback (most recent call last):
  File "/Users/username/ai/llama2.c/export_meta_llama_bin.py", line 11, in <module>
    from llama import Llama
ModuleNotFoundError: No module named 'llama'
`

**Comment by karpathy** [comment]
do you have the latest version of the code?

**Comment by pantol** [comment]
I updated the code and it worked. Thanks
