### ISSUE TITLE
‘CLOCK_REALTIME’ undeclared &  storage size of ‘time’ isn’t known

### ISSUE THREAD

**Issue by Rhuax** [karpathy/llama2.c#136]
Hi,

I'm having those 2 errors when running the make run command:
`run.c: In function ‘time_in_ms’:
run.c:373:21: error: storage size of ‘time’ isn’t known
     struct timespec time;
                     ^
run.c:374:5: warning: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
     clock_gettime(CLOCK_REALTIME, &time);
     ^
run.c:374:19: error: ‘CLOCK_REALTIME’ undeclared (first use in this function)
     clock_gettime(CLOCK_REALTIME, &time);
                   ^
run.c:374:19: note: each undeclared identifier is reported only once for each function it appears in
make: *** [run] Error 1`

Can someone help me?

**Comment by tairov** [comment]
Hi @Rhuax , please share OS version/specs.

**Comment by tairov** [comment]
@Rhuax which compiler do you have on your system? On most platforms all builds are successful ( latest ci https://github.com/tairov/llama2.c/actions/runs/5680020941 )

**Comment by Rhuax** [comment]
I'm on a ec2 instance in aws with amazon linux:
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Comment by tairov** [comment]
@Rhuax see this PR #139 , actually for older versions of gcc need to add compilation option `-std=gnu11`
Now on Amazon Linux & Centos `run.c` compiles fine:

```
$ gcc -Ofast -std=gnu11 -o run run.c -lm
./run model110m.bin
<s>
 Once upon a time, there was a little girl named...
...
achieved tok/s: 28.378229
```
