### ISSUE TITLE
Could model export to onnx?

### ISSUE THREAD

**Issue by taowucn** [karpathy/llama2.c#142]
Hello! When I'm try export it to ONNX, it encounters below error.  Do you have any idea for this?

torch.onnx.export(model, x, onnx_model,
                  export_params=True, verbose = True, do_constant_folding=True,
                  input_names=input_names,
                  output_names=output_names)
                  
RuntimeError: ScalarType ComplexFloat is an unexpected tensor scalar type.

**Comment by karpathy** [comment]
There's a PR with a fix, I just haven't gotten around to it.

**Comment by taowucn** [comment]
Fixed. Thanks.

**Comment by karpathy** [comment]
Was merged
