### ISSUE TITLE
KeyError: 'optimizer'

### ISSUE THREAD

**Issue by myan-o** [karpathy/llama2.c#148]
````bash
wget https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.pt -P out
mv out/stories15M.pt out/ckpt.pt
python train.py
````

tokens per iteration will be: 131,072
breaks down as: 4 grad accum steps * 1 processes * 128 batch size * 256 max seq len
Resuming training from out
num decayed parameter tensors: 43, with 15,187,968 parameters
num non-decayed parameter tensors: 13, with 3,744 parameters
using fused AdamW: False
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    optimizer.load_state_dict(checkpoint["optimizer"])
KeyError: 'optimizer'

**Comment by karpathy** [comment]
ugh... it's because i removed the optimizer state from the checkpoint. it's very large because the Adam optimizer holds 2 separate copies of the parameters, holding their first and second moments. if you simply uncomment that line it should work?

**Comment by karpathy** [comment]
just fixed it on master
