### ISSUE TITLE
Issue with Chinese Dataset and Model Inference

### ISSUE THREAD

**Issue by chengshenlian** [karpathy/llama2.c#158]
I am using Linux Ubuntu 20.04 for my project. I have utilized a Chinese dataset, which consists of 57 files, with each file containing 10,000 data entries. Here's an example of the data format:

['story': '巫山高，巫女妖。雨爲暮兮雲爲朝，楚王顦顇魂欲銷。秋猨嗥嗥日將夕，紅霞紫煙凝老壁。千巖萬壑花皆坼，但恐芳菲無正色。不知今古行人行，幾人經此無秋情。雲深廟遠不可覓，十二峰頭插天碧.' ...]

While I managed to train the model using the Chinese dataset, I encountered an issue with character encoding during model inference. The output contains garbled characters.

I wanted to know if this training approach fully supports Chinese text, or if there are specific modifications required for data preprocessing (tokenization) or training code to handle Chinese characters properly. Are there any specific requirements for the data format used in the training process?
![image](https://github.com/karpathy/llama2.c/assets/134602920/5d378c3a-4f56-4201-a6d4-e5693f2bc8c0)

Screenshot of Trained Model:
![image](https://github.com/karpathy/llama2.c/assets/134602920/967b30cc-2812-4ac0-9186-addf4ef682e8)

Looking forward to your guidance.

**Comment by kevinmeehanofficial** [comment]
I've experienced this with an English dataset for a different model, and looking at your screenshot, it seems your model is overfitting or underfitting.  Look at the training loss and the validation loss at the saved checkpoint. An optimally trained model will have a train loss and val loss that is almost identical. In most of my models, the value loss is a little less than the train loss. 

It's hard to tell seeing only one screenshot, so there could be a couple of things causing this:
1. Underfitting: You have a validation dataset that is too different than your training data set (you can try adding more data to your training dataset and training for longer)
2. Overfitting: The val and training loss were similar, but you trained too long, causing the model to fit the data too much. For some reason, when this happens, the validation loss can jump higher than it was.  Try training for less time in this case. Overfit models can not generalize well. 

Monitor each model checkpoint to see how the val loss and train loss are moving, and let me know if you need more help troubleshooting.

**Comment by musellama** [comment]
> I can't speak on whether the model will work well with Chinese.
> 
> However, I've experienced this with an English dataset for a different model, and looking at your screenshot, it seems your model is overfitting or underfitting. Look at the training loss and the validation loss at the saved checkpoint. An optimally trained model will have a train loss and val loss that is almost identical. In most of my models, the value loss is a little less than the train loss.
> 
> It's hard to tell seeing only one screenshot, so there could be a couple of things causing this:
> 
> 1. Underfitting: You have a validation dataset that is too different than your training data set (you can try adding more data to your training dataset and training for longer)
> 2. Overfitting: The val and training loss were similar, but you trained too long, causing the model to fit the data too much. For some reason, when this happens, the validation loss can jump higher than it was.  Try training for less time in this case. Overfit models cannot generalize well.
> 
> Monitor each model checkpoint to see how the val loss and train loss are moving, and let me know if you need more help troubleshooting.

There is this error

return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)
You know how this error is caused，Is it a problem with the cuda version mine is 12.0

**Comment by kroggen** [comment]
@chengshenlian make sure you are using the last version (`git pull`)

There was some changes on [this commit](https://github.com/karpathy/llama2.c/commit/b4bb47bb7baf0a5fb98a131d80b4e1a84ad72597#diff-d4130038ec752c21e16a6f228bf18be04dcf8b8ed68402f3d0c80d2fd6209104R58) that encodes the tokens in UTF-8 format

Maybe that is the reason

**Comment by musellama** [comment]
@chengshenlian 
可以加个联系方式嘛？

**Comment by tnmthai** [comment]
Hi all,

I would like to know which data will be trained from JSON.
We have:
`Index 0
  Key: story
  Key: instruction
    Key: prompt:
    Key: words
      Index 0
      Index 1
      Index 2
    Key: features
      Index 0
  Key: summary
  Key: source`

It will take all information or just only `Key: story`? If only 1, can we use csv or txt file?

Thanks all.

**Comment by tnmthai** [comment]
> I am using Linux Ubuntu 20.04 for my project. I have utilized a Chinese dataset, which consists of 57 files, with each file containing 10,000 data entries. Here's an example of the data format:
> 
> ['story': '巫山高，巫女妖。雨爲暮兮雲爲朝，楚王顦顇魂欲銷。秋猨嗥嗥日將夕，紅霞紫煙凝老壁。千巖萬壑花皆坼，但恐芳菲無正色。不知今古行人行，幾人經此無秋情。雲深廟遠不可覓，十二峰頭插天碧.' ...]
> 
> While I managed to train the model using the Chinese dataset, I encountered an issue with character encoding during model inference. The output contains garbled characters.
> 
> I wanted to know if this training approach fully supports Chinese text, or if there are specific modifications required for data preprocessing (tokenization) or training code to handle Chinese characters properly. Are there any specific requirements for the data format used in the training process? ![image](https://user-images.githubusercontent.com/134602920/256835852-5d378c3a-4f56-4201-a6d4-e5693f2bc8c0.png)
> 
> Screenshot of Trained Model: ![image](https://user-images.githubusercontent.com/134602920/256836240-967b30cc-2812-4ac0-9186-addf4ef682e8.png)
> 
> Looking forward to your guidance.

Hi @chengshenlian 

Can I please ask you how to create a dataset like you did? For example, I have some pdf files and want to convert to json with the same format for Llama 2? Can you share your code?

Kind regards
Thai

**Comment by kroggen** [comment]
I highly recommend watching this video for those wanting to train or fine-tune a Llama2-based model:

https://youtu.be/ThKWQcyQXF8?t=506

That can also be the cause of the UTF-8 problems, the `sentencepiece` tokenizer

**Comment by zhangtj1996** [comment]
My env is Win and I met the similar problem in Powershell. `chcp 65001` didn't help in powershell, but did help in CMD.
