### ISSUE TITLE
How can we obtain the config of Llama 2 architecture?

### ISSUE THREAD

**Issue by mwmercury** [karpathy/llama2.c#177]
I truly appreciate your amazing work! It helps beginners like me a lot.
Can I ask a silly question?

How do you obtain the config of Llama 2 architecture? As I can see, there is a `model.py` file containing the definitions of some layers and operations. However, I am unsure how to determine, for example, the types of layers that Llama uses or the detailed config of those layers, such as the number of channels/dimensions.
Is the model architecture described in the original paper or elsewhere?

Thank you in advance.

**Comment by RahulSChand** [comment]
It depends on the size of the model you are using. 7B, 15B parameter. But you can get all configs from huggingface or the paper

Search for the "<model-name> hugging face config.json" and you will find it. For example, llama-7B : https://huggingface.co/huggyllama/llama-7b/blob/main/config.json

Or you can refer to this table from the original llama paper 

<img width="918" alt="image" src="https://github.com/karpathy/llama2.c/assets/16897807/5b131e4c-e85d-4586-9652-63c93ffa2023">

**Comment by mwmercury** [comment]
Thank you so much for the detailed reply!
