### ISSUE TITLE
Waiting for next YouTube video

### ISSUE THREAD

**Issue by SkalskiP** [karpathy/llama2.c#2]
Hi, @karpathy 👋🏻! Awesome project. Will you release a complementary YouTube video where you explain everything?

**Comment by karpathy** [comment]
I'll see if I can do a quick one, ok.

**Comment by karpathy** [comment]
Ok btw update I decided not to do a quick one. Current plan is to get this repo into a nice final state that I'm happy with, then I'll try to build it again from scratch with a video walkthrough, as my other series. We're not actually all that far off from this repo being in a nice and happy place. Big remaining things are just int8 quantization, UTF-8, Chat model, and LoRA finetunes. Closing.
