### ISSUE TITLE
Support inference with LLAMA 2 70B model

### ISSUE THREAD

**Issue by raimondasl** [karpathy/llama2.c#210]
Currently inference fails with LLAMA 2 70B model even with the code that fixes 13B model inference.
Something is causing incorrect size calcs for `w->freq_cis_real` at least. It might be due to `n_kv_heads` and `n_heads` difference for 70B model. But there might be other differences that are causing export or import issues.

I'll add any additional info I have from my debugging runs later.

**Comment by janimo** [comment]
can you retry with the latest code?

**Comment by raimondasl** [comment]
llama-2-70B model works with latest code if I export it with old script:

```
OMP_NUM_THREADS=4 ./run llama-2-70b.bin -n 25 -i "Once upon a time"
Once upon a time, there was a young guy who spent most of his life waiting for things to happen. He hoped
achieved tok/s: 0.010036
```

I am closing the issue.

**Comment by obhalerao97** [comment]
Llama2-13B malloc is failing, same code works for 7B, not sure what I'm doing wrong?
