### ISSUE TITLE
stories110M.bin Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by rophy-zhang** [karpathy/llama2.c#213]
>> ./run stories110M.bin 0.9 1024 "who are you"
Segmentation fault (core dumped)

The above error occurs, both 15M and 42M models have no problem.
The Linux system environment is Ubuntu 16.04, and the version of make is 4.2.

**Comment by pharrellyhy** [comment]
make sure the model you downloaded is complete. the stories110M.bin model is proximate 420M size on disk

**Comment by rophy-zhang** [comment]
Thanks for the answer, the data transmission process is lost.

**Comment by twobob** [comment]
Can this be closed?
