### ISSUE TITLE
Why do we use use 2*max_seq_len in RoPE embedding?

### ISSUE THREAD

**Issue by RahulSChand** [karpathy/llama2.c#220]
https://github.com/karpathy/llama2.c/blob/af8708d87bcda7fda97b93f6c135dd43ea78106c/model.py#L218-L219

We pass 2*max_seq_length but in for all forward passes & while saving model we truncate it to first `:max_seq_length` elements. 

If this is some training only hack then I don't see this in reference huggingface [implementation](https://github.com/huggingface/transformers/blob/2bd7a27a671fd1d98059124024f580f8f5c0f3b5/src/transformers/models/llama/modeling_llama.py#L92 ) of RoPE

**Comment by RahulSChand** [comment]
Looks like this 2*max_seq_length is present in the official llama repo itself (but not in huggingface llama). Closing this

**Comment by RahulSChand** [comment]
Looks like this 2*max_seq_length is present in the official llama repo itself (but not in huggingface llama). Closing this

**Comment by kroggen** [comment]
It may be because it uses 2 floats for each position, as it is a complex number: the real and the imaginary parts
