### ISSUE TITLE
How to export llama2_7b_hf.bin instead of llama2_7b.bin?

### ISSUE THREAD

**Issue by overheat** [karpathy/llama2.c#227]
I found llama-2-7b-hf on [huggingface](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) 

How to convert from llama2_7b.bin to llama2_7b_hf.bin?

**Comment by RahulSChand** [comment]
This might help
[convert_llama_weights_to_hf.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py) 

This maps llama2_7b.bin to llama2_7b_hf.bin. You can change the script to do the reverse conversion

**Comment by aclie** [comment]
do u know how to covert nanogpt ckpt.pt to model.bin?

**Comment by Nick-infinity** [comment]
For HF model we can use #286 

I have tested it but I am not sure about the freq_img and freq_real part though. I think it should work

**Comment by karpathy** [comment]
Script for this just merged.
