### ISSUE TITLE
I just want to say thank you

### ISSUE THREAD

**Issue by metalwhale** [karpathy/llama2.c#235]
Your work is absolutely amazing. I now have a firm grasp of the overall architecture of the Transformer. Additionally, I have gained a deep understanding of every single operation and weight in the Transformer network by studying your code.

I can even create my implementation from scratch using Zig, with your code as a valuable reference!

Thank you so much for sharing this with us. 🤗🤗

(I can't think of a better place to express all of this than on the GitHub issue. My apologies for any inconvenience.)

**Comment by karpathy** [comment]
👍 great, working as intended! :)

**Comment by metalwhale** [comment]
issue closed with faith 😉😉
