### ISSUE TITLE
What is it `assert 0 <= 1 < ndim`?

### ISSUE THREAD

**Issue by ademyanchuk** [karpathy/llama2.c#259]
Hi, thanks for the inspiration! I was really trying to figure it out myself, googled it., asked ChatGPT, no answer... What on earth does `assert 0 <= 1 < ndim` it mean? From the function bellow.

```python
def reshape_for_broadcast(freqs_cos: torch.Tensor, freqs_sin: torch.Tensor, x: torch.Tensor):

    ndim = x.ndim
    assert 0 <= 1 < ndim
    assert freqs_cos.shape == freqs_sin.shape == (x.shape[1], x.shape[-1] // 2)
    shape = [1] * ndim
    shape[1] = x.shape[1]
    shape[-1] = x.shape[-1] // 2

    return freqs_cos.view(*shape), freqs_sin.view(*shape)
```

Thank you in advance!

**Comment by twobob** [comment]
> Given the shape constraints specified in the code:
> 
>     freqs_cos.shape == freqs_sin.shape == (x.shape[1], x.shape[-1] // 2)
>     shape[1] = x.shape[1]
>     shape[-1] = x.shape[-1] // 2
>     All other dimensions have a size of 1
> 
> This reshaping allows for broadcasting across other dimensions of x, in accordance with NumPy's broadcasting rules. Specifically, two dimensions are compatible for broadcasting if:
> 
>     They are equal, or
>     One of them is 1
> 
> By reshaping freqs_cos and freqs_sin in this way, you're ensuring that they can be broadcast across x along dimensions where the size of x is not 1, as long as the constraints on the shapes are satisfied.
> 
> The requirement that ndim > 1 (implied by the assert statement) seems to ensure that x has at least two dimensions, so this reshaping would make sense in that context. Without knowing the exact operations you're planning to perform with these tensors, it's hard to say more specifically what the broadcasting is intended to accomplish, but the reshaping does appear to be consistent with the standard broadcasting rules.
> 

maybe they just meant ndim > 1
