### ISSUE TITLE
./run cannot load tokenizer.bin generated from custom tokenizer.model

### ISSUE THREAD

**Issue by saltyduckegg** [karpathy/llama2.c#263]
I have trained a custom tokenizer using SentencePiece and saved the tokenizer.model file. I can use this file to tokenize my data correctly. However, when I try to run the run with my model.

it fails to load the tokenizer.bin file that is generated from the tokenizer.model file. It shows a strange error like this:
![image](https://github.com/karpathy/llama2.c/assets/88698765/dd370837-0e41-4ec3-967d-d079de5d6e92)

i think the tokenizer is not broken:
![image](https://github.com/karpathy/llama2.c/assets/88698765/7c4ece2f-8cc9-4892-82b5-9781d022882b)

**Comment by atamurad** [comment]
What is the vocabulary size? Does it match the value in the model.bin file? 

if you change the tokenizer, you have to change/retrain the transformer model as well.

**Comment by saltyduckegg** [comment]
100 onlly just for a simple test

**Comment by saltyduckegg** [comment]
thank you very much!

I will give you feedback after I try again.


> What is the vocabulary size? Does it match the value in the model.bin file?
> 
> if you change the tokenizer, you have to change/retrain the transformer model as well.

**Comment by saltyduckegg** [comment]
> What is the vocabulary size? Does it match the value in the model.bin file?
> 
> if you change the tokenizer, you have to change/retrain the transformer model as well.

![image](https://github.com/karpathy/llama2.c/assets/88698765/fe3e89b1-8d97-44a8-8584-8e892cf631d7)
thank you ,it's useful for me .  : D

i found the vocabulary size is unmatch in the tokenizer.model and the trained model  before
