### ISSUE TITLE
TypeError("get_tokenizer_model_path() missing 1 required positional argument: 'vocab_size'")

### ISSUE THREAD

**Issue by gereoffy** [karpathy/llama2.c#280]
there is a bug in tinystories.py:

in process_shard() the get_tokenizer_model_path() func is called without any args, but it's defined to expect a mandatory arg vocab_size:

def get_tokenizer_model_path(vocab_size):

Note, that exceptions are ignored and silenced inside process_shard()...

**Comment by mihainadas** [comment]
Can confirm.

**Comment by karpathy** [comment]
sorry about that and ty for pr closing
