### ISSUE TITLE
Can this run on the CPU?

### ISSUE THREAD

**Issue by Kayce001** [karpathy/llama2.c#29]
Can this run on the CPU?

**Comment by dronesflier** [comment]
This runs on the CPU.

**Comment by Kayce001** [comment]
> This runs on the CPU.
gpu?
when i run it on cpu, i get no answer.

**Comment by adeeb10abbas** [comment]
Can you share your steps of what you're doing...

**Comment by karpathy** [comment]
This only runs on CPU right now.
