### ISSUE TITLE
-n 0 makes no tokens (21/08/2023 pulls)

### ISSUE THREAD

**Issue by twobob** [karpathy/llama2.c#334]
$env:OMP_NUM_THREADS=4; ./run ../out/model15M.bin -z ..\out\tok32k.bin -t .9 -p 0 -n 0 -s 42  -i "Varsa ran"

$env:OMP_NUM_THREADS=4; ./run ../out/model15M.bin -z ..\out\tok32k.bin -t .9 -p 0 -n 256 -s 42  -i "Varsa ran"
Varsa ran on the grass, more stuff Vysys laughedly and had a lot of fun.
achieved tok/s: 80.089820

I'll have a poke around

**Comment by twobob** [comment]
[#336](https://github.com/karpathy/llama2.c/pull/336/) if desired

**Comment by karpathy** [comment]
fixed now
