### ISSUE TITLE
Possible issue in decode()

### ISSUE THREAD

**Issue by xefoci7612** [karpathy/llama2.c#340]
There is no actual skip if condition `(isprint(byte_val) || isspace(byte_val))` is false, the '<0x01>' type piece is printed verbatim instead of being ignored/skipped as the comment seems to suggest.

```C
    if (sscanf(piece, "<0x%02hhX>", &byte_val) == 1) {
        // ok this token is a raw byte token, careful to only print printable chars or whitespace
        // some of the other bytes can be various control codes, backspace, etc. => skip
        if (isprint(byte_val) || isspace(byte_val)) {
            t->byte_piece[0] = byte_val;
            piece = &t->byte_piece[0];
        }
    }

```

**Comment by karpathy** [comment]
Yes it's a poor comment. By skip I meant more "passthrough". I believe the functionality is correct.

**Comment by karpathy** [comment]
Oh wait maybe I'm confused

**Comment by karpathy** [comment]
I think you're right that this is wrong. Wires got a bit crossed during the refactor here. I'll push a fix.

**Comment by karpathy** [comment]
Attempted a fix here, @xefoci7612 what do you think?

https://github.com/karpathy/llama2.c/commit/7ac65cb2c2b169050747be92011b7bebdd1b4544

**Comment by xefoci7612** [comment]
This is a very general solution. 

In my mind I had a more limited one, simply following the comment and skip in case piece is not printable, for instance by returning an empty string.

```diff
char* decode(Tokenizer* t, int prev_token, int token) {
         // some of the other bytes can be various control codes, backspace, etc. => skip
         if (isprint(byte_val) || isspace(byte_val)) {
             t->byte_piece[0] = byte_val;
-            piece = &t->byte_piece[0];
+        } else {
+            // return an empty string if char is not printable
+            t->byte_piece[0] = '\0';
         }
+        piece = &t->byte_piece[0];
     }
     return piece;
 }
```

**Comment by xefoci7612** [comment]
OK ty for explanation
