### ISSUE TITLE
how to use this project to make a chatbot?

### ISSUE THREAD

**Issue by 9crk** [karpathy/llama2.c#35]
sorry for my lackness of the knowlege of llama2.
does this code only archive certain centence generating?
how to make a chatbot ?

**Comment by karpathy** [comment]
It can be a chatbot with very light tweaks if you train it on chatbot data. Something we could look into over time. For now it's a token sampler / base model, see my Microsoft BUILD talk https://www.youtube.com/watch?v=bZQun8Y4L2A

**Comment by 9crk** [comment]
Cant wait to see that happen. Thanks! Im going to make this model running on some cheap chips.

**Comment by karpathy** [comment]
kk. Just to clarify my previous response: The fact that the current model is not a chatbot is 99% a matter of the training dataset, and 1% because you have to build the UI/UX where you take keyboard input and feed it in in turns.
