### ISSUE TITLE
Training Time? (Thanks so much)

### ISSUE THREAD

**Issue by amrrs** [karpathy/llama2.c#4]
Thanks so much for the project.

Curious about how much time it took for you to train and did you use the same cloud resources as in the inference one?

Thanks!

**Comment by karpathy** [comment]
Current settings train for few hours (~2?) on 4XA100 40GB that I use from [Lambda Cloud](https://lambdalabs.com) <3. But I think they look very short on GPUs these days.

**Comment by amrrs** [comment]
Thanks so much!
