### ISSUE TITLE
The inferenced text has a leading space because of the vocab

### ISSUE THREAD

**Issue by Zardinality** [karpathy/llama2.c#41]
Debugged to the first token emerged:

<img width="669" alt="image" src="https://github.com/karpathy/llama2.c/assets/13702822/9d9b464b-b762-45bd-b2cc-efda95729454">

And confirmed by using python model directly:

<img width="543" alt="image" src="https://github.com/karpathy/llama2.c/assets/13702822/1b636eaa-a274-417e-b55e-5161d455717d">

Clearly the tokenizer model count `▁Once` instead of `Once` as a token. Note that `sentencepiece` [use ▁ as space](https://github.com/google/sentencepiece#:~:text=a%20meta%20symbol-,%22%E2%96%81%22%20(U%2B2581),-as%20follows.).

**Comment by karpathy** [comment]
Yes, the vocab itself has this space. But somehow when you ask sentencepiece to decode a token sequence, it doesn't print this leading space.
