### ISSUE TITLE
casual attention implementation

### ISSUE THREAD

**Issue by liecn** [karpathy/llama2.c#469]
After examining the code, I find it a bit unclear how the causal attention is implemented. Specifically, I'm seeking clarification on how the mask in the following Python code can be translated into a C implementation.

![image](https://github.com/karpathy/llama2.c/assets/32219716/529c239d-8a92-4e18-930b-80057b3b3dba)
![image](https://github.com/karpathy/llama2.c/assets/32219716/d9440e8f-bb1c-4bc7-b6f8-dcaef9c97a85)

Thanks!

**Comment by liecn** [comment]
Ohh, I see. Thanks,  Giles!

Does this imply that I can eliminate the casual attention (i.e., the mask) by directly removing that part in the Python code for training, without requiring any changes in the C implementation for inference?

**Comment by GilesBathgate** [comment]
@liecn When training, you provide the complete sequence to the self-attention heads. However, it's crucial to mask out scores that represent affinities between past tokens and future tokens. This ensures that the model only calculates affinities between tokens that precede any given token.

If you don't implement a causal mask, the model won't be trained to be autoregressive (i.e., capable of predicting the future). Instead, it will function as a bag-of-words model, lacking the ability to capture sequential relationships.
