### ISSUE TITLE
How to quantize stories15M.bin

### ISSUE THREAD

**Issue by forcekeng** [karpathy/llama2.c#476]
Hi, I want know how to quantize `stories15M.bin` or `stories42M.bin`. I try to use `python export.py`, it shows no `params.json`.

![image](https://github.com/karpathy/llama2.c/assets/116548753/a7c8cdb3-3ef4-4d84-8a4b-8d2f0df2841d)

**Comment by 2point718** [comment]
if you have a checkpoint file .pt

`$ python export.py stories15M_q8.bin --version 2 --checkpoint out/ckpt.pt`
