### ISSUE TITLE
[Suggestion] Enable Discussion

### ISSUE THREAD

**Issue by trholding** [karpathy/llama2.c#492]
Dear Andrej

Could you enable discussions for this repo. That would help folks to ask questions in discussions instead of issues. For example I have a few questions regarding running training on colab and I do not wish to pollute issues.

**Comment by marcindulak** [comment]
When making a decision about this, please be aware of the limitation of github discussions - they don't auto-backlink to issues and discussions https://github.com/orgs/community/discussions/2971
