### ISSUE TITLE
Everyone, I have implemented multi-token prediction of InfiniAttention and meta.

### ISSUE THREAD

**Issue by win10ogod** [karpathy/llama2.c#518]
Is anyone willing to help improve memory consumption?
I will post a PR.
(https://github.com/win10ogod/llama2-InfiniAttention.c/blob/master/model.py)
I commented out`model_export(raw_model, os.path.join(out_dir, "model.bin"), version=0)`
Because I don’t understand C language, there are also errors in export .py

**Comment by bityigoss** [comment]
if we still tie the weights of lm_head in multi-token prediction, how they output different token predictions? @win10ogod

**Comment by Altabeh** [comment]
When I try to run test_python() function, I get 

`Traceback (most recent call last):
  File "projects/llama2.c/test_all.py", line 101, in <module>
    test_python()
  File "projects/llama2.c/test_all.py", line 89, in test_python
    y = model.generate(x, max_new_tokens=200, temperature=0.0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "projects/llama2.c/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "projects/llama2.c/model.py", line 474, in generate
    idx = torch.cat((idx, idx_next), dim=1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Tensors must have same number of dimensions: got 2 and 3`

Are you sure this works? @win10ogod

**Comment by win10ogod** [comment]
> When I try to run test_python() function, I get 
> 
> `Traceback (most recent call last):
>   File "projects/llama2.c/test_all.py", line 101, in <module>
>     test_python()
>   File "projects/llama2.c/test_all.py", line 89, in test_python
>     y = model.generate(x, max_new_tokens=200, temperature=0.0)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "projects/llama2.c/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "projects/llama2.c/model.py", line 474, in generate
>     idx = torch.cat((idx, idx_next), dim=1)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: Tensors must have same number of dimensions: got 2 and 3`
> 
> Are you sure this works? @win10ogod 


 I'm sure it's invalid because the current PR modeling is invalid. I'm sorry for causing you trouble. 

I will close the question
