### ISSUE TITLE
add prompt

### ISSUE THREAD

**Issue by myan-o** [karpathy/llama2.c#56]
Allow prompt to be specified as a string on the command line.

````bash
Usage: ./run  model44m.bin 0.9 200 "I'm cat!!"
or
Usage: ./run  model44m.bin 0.9 200 "`cat prompt.txt`"
````

I created the following function.
Any string can be inserted.
Chat format can be easily created by using this function.
````run.c
int transformer_str(char *input, int pos, Config* p, RunState* s, TransformerWeights* w, char **vocab) {
    while (input[0] != 0) {
        int next = -1;
        int next_length = 0;
        for (int i = 0; i < p->vocab_size; i++) {
            char *v = vocab[i];
            int j = 0;
            int hit = 1;
            while (v[j] != 0) {
                 if (v[j] != input[j]) {
                    int hit = 0;
                    break;
                }
                ++j;
            }
            if (hit && j > next_length) {
                next_length = j;
                next = i;
            }
        }

        if (0 > next) return pos;

        pos++;
        transformer(next, pos, p, s, w);

        printf("%s", vocab[next]);
        fflush(stdout);

        input += next_length;
    }

    return pos;
}
````

**Comment by myan-o** [comment]
Match the longest conversation.
Not sure if this spec is correct.

**Test**
./run  model44m.bin 0.9 200 "My name is"
<s>
My name is Lucy. Every day, she goes outside to play in the snow. One day, she decided to go on a snow castle. 
When she got to the moat, Lucy was so excited. She found a big, thick cave and started to explore.

**Comment by kroggen** [comment]
Now it supports prompt. Added on [this commit](https://github.com/karpathy/llama2.c/commit/b4bb47bb7baf0a5fb98a131d80b4e1a84ad72597)
