### ISSUE TITLE
Softmax experiment 

### ISSUE THREAD

**Issue by generalsvr** [karpathy/llama2.c#59]
Hello, Andrej! 

Have you seen [this blog post? ](https://www.evanmiller.org/attention-is-off-by-one.html)  The author states that he found a "bug" in the attention mechanism that affects all transformers nowadays. In order to test this theory we need to train a model from scratch and compare the results. The fix is very easy, just add 1 to the softmax. What do you think?

**Comment by karpathy** [comment]
I saw it; Worth trying, but unrelated to repo :)
