### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by aneeshjoy** [karpathy/llama2.c#61]
I get the following compilation error. compiling on Android, termux with gcc. Its a Snapdragon 8 Gen 2 chip.

~/llama2.c $ make
gcc -O3 -o run run.c -lm
run.c:359:3: error: call to undeclared function 'timespec_get'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]         timespec_get(&time, TIME_UTC);                          ^                                                     1 error generated.                                      make: *** [Makefile:5: run] Error 1

~/llama2.c $ termux-info                                
....
Kernel build information:
Linux localhost 5.15.74-android13-8-o-gfb3eff09eff0 #1 SMP PREEMPT Mon May 22 01:39:13 UTC 2023 aarch64 Android
Device manufacturer:
OnePlus
Device model:
CPH2449
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by emma-eva** [comment]
fixed on here: https://github.com/karpathy/llama2.c/pull/60

**Comment by aneeshjoy** [comment]
tested. the fix works!
