### ISSUE TITLE
 How do I add my own prompt 

### ISSUE THREAD

**Issue by StudyingLover** [karpathy/llama2.c#64]
I found that the result will be output directly after running `./run out/model.bin`, I want to know how I can add my own prompt

**Comment by xiscoding** [comment]
## JANK SOLUTION 1
   I added these code blocks, It only inferences one prompt at a time. And after retraining on Alpha-CoT (it is a poo poo dataset) my results are pretty incoherent. What data set would you retrain on?

```
// 'checkpoint' and 'input_sequence' are necessary args
    if (argc < 3) {
        printf("Usage: %s <checkpoint_file> <input_sequence> [temperature] [seed]\n", argv[0]);
        return 1;
    }
    checkpoint = argv[1];
    char *input_sequence_str = argv[2];
    // temperature is optional
    if (argc >= 4) {
        temperature = atof(argv[3]);
    }
    // seed is optional
    if (argc >= 5) {
        unsigned int seed = atoi(argv[4]);
        srand(seed);
    } else {
        time_t current_time; 
        time(&current_time);
        srand((unsigned int)current_time);
    }

    // call Python script to tokenize input sequence
    char command[2048];  // make sure this is large enough
    sprintf(command, "python pretokenize.py \"%s\"", input_sequence_str);
    FILE *pipe = popen(command, "r");
    if (!pipe) {
        printf("Unable to open pipe!");
        return 1;
    }

    // read tokenized input sequence from pipe
    int input_sequence[MAX_INPUT_LENGTH];
    int input_length = 0;
    while (fscanf(pipe, "%d", &input_sequence[input_length]) == 1) {
        input_length++;
        
    }
    //printf("input_length: %d", input_length);
    pclose(pipe);

 ```
### Then to init the model state

``` 
// initialize the model's state with the input sequence
    int next;
    int pos = 0;

    
    for (int i = 0; i < input_length; i++) {
        transformer(input_sequence[i], pos, &config, &state, &weights);
        pos++;
        next = input_sequence[i];  // add this line

    }

    // start generating the output sequence after the input sequence
    while (pos < config.seq_len) {

        // forward the transformer to get logits for the next token
        transformer(next, pos, &config, &state, &weights);
```

Then I changed the run wrap file to work with input sequences. There isn't a run_wrap file anymore Im not sure how they are decoding the tokens. If you make this better please let me know.

**Comment by StudyingLover** [comment]
> ## 卡顿解决方案 1
> 我添加了这些代码块，它一次只推断一个提示。在 Alpha-CoT（它是便便数据集）上重新训练后，我的结果非常不连贯。您将使用什么数据集进行重新训练？
> 
> ```
> // 'checkpoint' and 'input_sequence' are necessary args
>     if (argc < 3) {
>         printf("Usage: %s <checkpoint_file> <input_sequence> [temperature] [seed]\n", argv[0]);
>         return 1;
>     }
>     checkpoint = argv[1];
>     char *input_sequence_str = argv[2];
>     // temperature is optional
>     if (argc >= 4) {
>         temperature = atof(argv[3]);
>     }
>     // seed is optional
>     if (argc >= 5) {
>         unsigned int seed = atoi(argv[4]);
>         srand(seed);
>     } else {
>         time_t current_time; 
>         time(&current_time);
>         srand((unsigned int)current_time);
>     }
> 
>     // call Python script to tokenize input sequence
>     char command[2048];  // make sure this is large enough
>     sprintf(command, "python pretokenize.py \"%s\"", input_sequence_str);
>     FILE *pipe = popen(command, "r");
>     if (!pipe) {
>         printf("Unable to open pipe!");
>         return 1;
>     }
> 
>     // read tokenized input sequence from pipe
>     int input_sequence[MAX_INPUT_LENGTH];
>     int input_length = 0;
>     while (fscanf(pipe, "%d", &input_sequence[input_length]) == 1) {
>         input_length++;
>         
>     }
>     //printf("input_length: %d", input_length);
>     pclose(pipe);
> ```
> 
> ### 然后初始化模型状态
> ```
> // initialize the model's state with the input sequence
>     int next;
>     int pos = 0;
> 
>     
>     for (int i = 0; i < input_length; i++) {
>         transformer(input_sequence[i], pos, &config, &state, &weights);
>         pos++;
>         next = input_sequence[i];  // add this line
> 
>     }
> 
>     // start generating the output sequence after the input sequence
>     while (pos < config.seq_len) {
> 
>         // forward the transformer to get logits for the next token
>         transformer(next, pos, &config, &state, &weights);
> ```
> 
> 然后我更改了运行包装文件以处理输入序列。不再有 run_wrap 文件我不确定他们如何解码令牌。如果你能做得更好，请告诉我。
> 
> 编辑：这可能效果更好 [#62（评论）](https://github.com/karpathy/llama2.c/issues/62#issue-1819724122)

I don't have custom dataset, I want ti use open model to run directly. Your code is amazing, I will try it if it's merged

**Comment by kroggen** [comment]
Now it supports prompt. Added on [this commit](https://github.com/karpathy/llama2.c/commit/b4bb47bb7baf0a5fb98a131d80b4e1a84ad72597)

Usage details on the README
