### ISSUE TITLE
CUDA out of memory when exporting llama7b 

### ISSUE THREAD

**Issue by kRo0T** [karpathy/llama2.c#65]
I'm trying to export llama7b model on my local machine (it has rtx 3060 12gb which is not enough) using export_meta_llama_bin.py script and receiving cuda out of memory.
I see that in generation.py from llama module (in Meta repo) they hardcoded cuda usage.
Anyone knows how to make it run on cpu with minimal script modification?

**Comment by abdelhadi-azouni** [comment]
Facing a related issue 
and would love help to make this cpu only

**Comment by kRo0T** [comment]
Made a PR #78

**Comment by karpathy** [comment]
try with updated code
