### ISSUE TITLE
Error: Unable to open tokenizer file tokenizer.bin

### ISSUE THREAD

**Issue by aron502** [karpathy/llama2.c#66]
I encountered an issue while following the "Feel the Magic" instructions in the README. Specifically, when I ran the command `./run out/model.bin`, I received the following error message:
`Unable to open the tokenizer file tokenizer.bin! Run python tokenizer.py to convert tokenizer.model -> tokenizer.bin`

model.bin md5sum: 644db0bc012b405d6baf99559272ab11 
system: 6.4.5-arch1-1 
gcc: 13.1.1
file: https://github.com/karpathy/llama2.c/blob/98ec4ba23d0a4e4b091af4bd6166a60d007db2d0/run.c

**Comment by karpathy** [comment]
? Very strange, given as this file is just in the root directory of the repo?

**Comment by wuyudi** [comment]
I reproduce the problem.

You need to clone the whole repo, not just the `run.c`

**Comment by wuyudi** [comment]
![image](https://github.com/karpathy/llama2.c/assets/30024051/0a3625cd-e909-4c87-833f-3c3e56a349fa)
![image](https://github.com/karpathy/llama2.c/assets/30024051/35fa376f-48a7-4f0e-8695-1c23bab16ad7)

**Comment by wuyudi** [comment]
interesting :laughing: , I `echo > tokenizer.py` then the magic still works. So seems that the `run.c` check the file but does not use it.
![image](https://github.com/karpathy/llama2.c/assets/30024051/2daf204d-1dbd-4003-9d9d-d3d089e27848)

**Comment by aron502** [comment]
> I reproduce the problem.
> 
> You need to also put the `tokenizer.bin` in the same folder , not just the `run.c`

Thanks, this resolved the issue.
