### ISSUE TITLE
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!

### ISSUE THREAD

**Issue by abdelhadi-azouni** [karpathy/llama2.c#70]
Cloned the llama repo and copied the export_meta_llama_bin.py file then run:
torchrun --nproc_per_node 1 export_meta_llama_bin.py

I get  
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!

I'm on linux 16vCPUs 32G ram no GPU 

Is the code supposed to work without GPU?

**Comment by joey00072** [comment]
in export function try
`self = self.to(torch.device("cpu"))`

https://github.com/karpathy/llama2.c/blob/98ec4ba23d0a4e4b091af4bd6166a60d007db2d0/export_meta_llama_bin.py#L14

tell me if this works

**Comment by sha0coder** [comment]
is not the export() which claim the GPU, its Llama.build()

**Comment by abdelhadi-azouni** [comment]
still have the same error 
full traceback:

Traceback (most recent call last):
  File "/home/dev1/llama2.c/llama/export_meta_llama_bin.py", line 85, in <module>
    generator = Llama.build(
  File "/home/dev1/llama2.c/llama/llama/generation.py", line 62, in build
    torch.distributed.init_process_group("nccl")
  File "/home/dev1/.local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home/dev1/.local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1024, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(backend_prefix_store, group_rank, group_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1102) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/dev1/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/dev1/.local/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/dev1/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/dev1/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/dev1/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dev1/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
export_meta_llama_bin.py FAILED

**Comment by Foundation42** [comment]
I'm having the same problem.  I worked with ChatGPT to try and rewrite parts of the dependent llama library that requires the GPU and distributed support.  We got so far but other issues started popping up.

Looking at this export_meta_llama_bin.py it seems like it could maybe be rewritten not to require the dependency on the llama library at some point, that might be a lot better

**Comment by sha0coder** [comment]
that would be great, other option is publishing the exported llama2_7b.bin

**Comment by Foundation42** [comment]
> that would be great, other option is publishing the exported llama2_7b.bin

that would be nice

**Comment by karpathy** [comment]
> > that would be great, other option is publishing the exported llama2_7b.bin
> 
> that would be nice. probably won't happen because - "bypass license agreement" mularky

Exactly why I didn't. (Also it is 26GB)
I'm sorry to see this causing issues, it is silly that we need torchrun to export the weights. Would happily accept a PR fixing that.

**Comment by rlancemartin** [comment]
> > > that would be great, other option is publishing the exported llama2_7b.bin
> > 
> > 
> > that would be nice. probably won't happen because - "bypass license agreement" mularky
> 
> Exactly why I didn't. (Also it is 26GB) I'm sorry to see this causing issues, it is silly that we need torchrun to export the weights. Would happily accept a PR fixing that.

Ah, I see.  Also asked about a shared file since [export probably won't work](https://github.com/karpathy/llama2.c/issues/73) (easily) on a Mac (NCCL dependency).

**Comment by Foundation42** [comment]
Maybe someone can use the guts from convert.py in the llama.cpp project for the .pth model loading and merge it with this conversion and export code. I would do it but my Python is not that great. I'm a C/C++ guy.

**Comment by dontgetfoundout** [comment]
Check out this repo I saw linked in another discussion.  I don't have a Mac to try the code atm, but this may be a good starting point for the changes you need to get llama running there. 

https://github.com/krychu/llama/blob/main/README.md

**Comment by sudara** [comment]
I used this llama fork successfully on my M1 mac:

https://github.com/aggiee/llama-v2-mps

like so:

```
PYTORCH_ENABLE_MPS_FALLBACK=1 torchrun --nproc_per_node 1 export_meta_llama_bin.py
```

![Terminal - 2023-07-25 51@2x](https://github.com/karpathy/llama2.c/assets/472/5c16236a-e990-4228-9713-fa57f14c32be)

If you've already downloaded the model, in addition to moving the model folder into the `llama-v2-mps` repo, be sure to move `tokenizer.model` and `tokenizer_checklist.chk`.

Note: the model was doing ~3 tokens/s on 96 threads on linux.... I get about a token a minute out of the box... ctrl-C will be your best friend :) 

```
clang -Ofast -march=native run.c -lm  -o run 
```

I then did the following:

```
brew install libomp # get OpenMP
brew install llvm # get latest clang, apple clang is old
echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc # make it easy to find new clang
clang -Ofast -fopenmp -march=native run.c  -lm  -o run # recompile with OpenMP
```
and ran 

```
OMP_NUM_THREADS=8 ./run llama2_7b.bin
```

which is.... slightly faster....maybe...? I know nothing about OMP, but without it, CPU usage seems around 33%, with threads at 8 (matches num of cores on my M1 max) it seems to settle around 120% cpu. With threads at 32 (just to see) the cpus are more dominated at 400% — but tokens don't necessarily come faster.

Anyway! A great starting place for my needs (I'm interested in taking a crack at optimizing for apple/arm) but yeah... ctrl-C will be your best friend for now :)

**Comment by joey00072** [comment]
I've ported code for loading llama, 
https://github.com/karpathy/llama2.c/pull/71
Can someone test It (I don't have beefy machine 🥲 )
 Note:  <i>I have disabled `mps` backend since not everyone has mac and we are not using it anyways </i>
 
 CC: @sudara @abdelhadi-azouni @karpathy

**Comment by joey00072** [comment]
updated https://github.com/karpathy/llama2.c/pull/71#issuecomment-1650313364

**Comment by karpathy** [comment]
try with updated code :)
