### ISSUE TITLE
"sys/mman.h: No such file or directory"

### ISSUE THREAD

**Issue by nanowell** [karpathy/llama2.c#80]
<sys/mman.h> is a Unix header and is not available on Windows so no way to run natively. Any solutions?

**Comment by karpathy** [comment]
🤦‍♂️ this came with the memmap PR we merged yesterday... for now you should be able to hackily revert the old behavior that loads everything into RAM:

https://github.com/karpathy/llama2.c/commit/133ad3ffff606c6a6a277e5f161a62e2971d254c

I wonder how llama.cpp does this. cc @krzysztof-jusiak

**Comment by krzysztof-jusiak** [comment]
Yeah, that's problematic, actually windows has its own version `CreateFileMapping` and llama.cpp has ifdefs for it which adds complexity. Not sure what would be best action here, we can either go back to memory allocation but that would prevent 7B+ models to be used unless on machines with tons of memory; we can also add ifdefs to the code for windows but that would add tons of complexity, or we can revert the change and find another solution, or not support windows? Either solution will have some trade offs unless there is some other option to do it? we potential could do it manually and load it chunks or something but that again would add complexity.

**Comment by krzysztof-jusiak** [comment]
One option for windows could be to use https://github.com/alitrack/mman-win32 which has the same includes and interfaces?

**Comment by xefoci7612** [comment]
> Yeah, that's problematic, actually windows has its own version `CreateFileMapping` and llama.cpp has ifdefs for it which adds complexity. Not sure what would be best action here, we can either go back to memory allocation but that would prevent 7B+ models to be used unless on machines with tons of memory; we can also add ifdefs to the code for windows but that would add tons of complexity, or we can revert the change and find another solution, or not support windows? Either solution will have some trade offs unless there is some other option to do it? we potential could do it manually and load it chunks or something but that again would add complexity.

Sorry, but malloc() works on virtual memory and does not fail if allocation is bigger than physical memory, as long as the number of bytes requested can be expressed in the size_t argument. There will be swapping in the worst case....as with memory mapping BTW.

**Comment by nanowell** [comment]
I thing the best solution would involve using ifdefs to handle Windows separately and using a third-party library like mman-win32 to provide the necessary functionality.
It will add some complexity to the code, but it would allow for the use of LLMs on Windows without requiring a large amount of physical memory.
`malloc()` could be used as a quick and dirty solution, it might not be the best choice for a high-performance, memory-intensive application like a large language model.

**Comment by karpathy** [comment]
Leaning to agree to introduce a little bit of complexity to keep memmap, would accept a PR that adds Windows capability unless it gets too crazy.

**Comment by xunboo** [comment]
windows build is passing https://github.com/xunboo/llama2win

**Comment by tairov** [comment]
Added PR, to make current `run.c` windows compatible in the current repo
https://github.com/karpathy/llama2.c/pull/96

It also should simplify maintenance and CI workflows

**Comment by tairov** [comment]
Must be fixed after #130 merged
