### ISSUE TITLE
use tcc to run it

### ISSUE THREAD

**Issue by wuyudi** [karpathy/llama2.c#83]
it can't directly run by tcc, but change

```c
  timespec_get(&time, TIME_UTC);
```

to

```c
  clock_gettime(CLOCK_REALTIME, &time);
```

make the job. ref https://stackoverflow.com/questions/68335778/mingw-gcc-time-utc-undeclared

Though speed is slow, but it now much more tiny. (gcc vs tcc)

![image](https://github.com/karpathy/llama2.c/assets/30024051/ea4fb525-02b4-48b9-8d7f-6be2a1c89ee4)

**Comment by karpathy** [comment]
see commit from 1 hr ago, thank you
